---
helmDefaults:
  verify: false
  wait: true
  timeout: 600
  recreatePods: false
  force: false
environments:
  observability:
    values:
      - ../environments/observability.yaml
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami/

releases:
  - name: prometheus
    namespace: {{ requiredEnv "TARGET_NAMESPACE" }}
    chart: bitnami/prometheus-operator
    version: 0.17.1
    atomic: true
    values:
      - prometheus/values.yaml
  - name: grafana
    namespace: {{ requiredEnv "TARGET_NAMESPACE" }}
    chart: stable/grafana
    version: 5.0.26
    atomic: true
    values:
      - grafana/values.yaml